#!/bin/bash

FOLDER='/home/genomerussia/main/analysis/cnv/sv/GR/'


PSKOV="/home/genomerussia/main/analysis/cnv/sv/GR//GR0076/GR0076.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0081/GR0081.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0082/GR0082.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0087/GR0087.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0088/GR0088.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0089/GR0089.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0091/GR0091.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0092/GR0092.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0094/GR0094.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0095/GR0095.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0096/GR0096.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0097/GR0097.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0104/GR0104.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0105/GR0105.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0106/GR0106.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0107/GR0107.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0113/GR0113.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0114/GR0114.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0115/GR0115.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0121/GR0121.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0122/GR0122.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0123/GR0123.deviated.gain.bed "
NOVGOROD="/home/genomerussia/main/analysis/cnv/sv/GR//GR0307/GR0307.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0308/GR0308.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0309/GR0309.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0310/GR0310.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0311/GR0311.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0312/GR0312.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0313/GR0313.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0314/GR0314.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0331/GR0331.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0332/GR0332.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0333/GR0333.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0334/GR0334.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0335/GR0335.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0336/GR0336.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0338/GR0338.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0339/GR0339.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0340/GR0340.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0383/GR0383.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0384/GR0384.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR0385/GR0385.deviated.gain.bed "
YAK="/home/genomerussia/main/analysis/cnv/sv/GR//GR1102/GR1102.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1103/GR1103.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1104/GR1104.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1105/GR1105.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1106/GR1106.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1107/GR1107.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1111/GR1111.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1112/GR1112.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1113/GR1113.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1114/GR1114.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1115/GR1115.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1116/GR1116.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1118/GR1118.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1119/GR1119.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1121/GR1121.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1122/GR1122.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1124/GR1124.deviated.gain.bed /home/genomerussia/main/analysis/cnv/sv/GR//GR1125/GR1125.deviated.gain.bed"


multiIntersectBed -i ${PSKOV} | cut -f1,2,3,4,5 > /home/genomerussia/main/analysis/cnv/sv/GR/stats/dev/deviated.gain.pskov.bed
multiIntersectBed -i ${NOVGOROD} | cut -f1,2,3,4,5 > /home/genomerussia/main/analysis/cnv/sv/GR/stats/dev/deviated.gain.novgorod.bed
multiIntersectBed -i ${YAK} | cut -f1,2,3,4,5 > /home/genomerussia/main/analysis/cnv/sv/GR/stats/dev/deviated.gain.yakutsk.bed

