#!/usr/bin/env python

import sys
import argparse
import subprocess
import os
BIN_DIR = '/hive/groups/recon/projs/felidae/apps/mrfast-2.6.1.0/'
WORKING_DIR = '/hive/groups/recon/projs/antelope/comparative/TASABTOA/2015-03-05/cnv'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('reads',help='folder with reads')
    parser.add_argument('reference')
    parser.add_argument('output',help='folder for sam files')
    args = parser.parse_args()
    i = 0
    jobList = os.path.join(WORKING_DIR,'jobList') 
    with open(jobList,'w') as f:
        for file in os.listdir(args.reads):
            command = ' '.join([os.path.join(BIN_DIR,'mrfast'),'--search',args.reference,'--seq', os.path.join(args.reads,file),'-o',os.path.join(args.output,file+'.sam')])
            f.write(command+'\n')
    subprocess.check_call(['para', 'make', jobList, '-ram=16g', '-maxJob=50'])
    subprocess.check_call(['para', 'push'])
    subprocess.check_call(['para', 'check'])
