#!/usr/bin/env python

import sys
import argparse
import numpy
import gzip
from Bio import SeqIO

START_1 = 9
END_1 = 45
START_2 = 45
END_2 = 81


def parse(reads):
    with open(reads) as f:
        while True:
            name = f.readline()
            if not name:
                return
            name=name.split()[0]
            bases = f.readline()
            strand = f.readline()
            quality = f.readline()
            if len(bases) > 82:
                print name+':1'
                print bases[START_1:END_1]
                print name+':2'
                print bases[START_2:END_2]
            elif len(bases) < 55:
                print bases.strip()
            else: 
                print 'read length is ', len(bases)
                print 'see split_reads for understanding'
                exit()
            return

def read_reads(reads):
    with gzip.open(reads,"rt") as handle:
        for seq_record in SeqIO.parse(handle, "fastq"):
            print '>'+seq_record.id+':1'
            print seq_record.seq[START_1:END_1]
            print '>'+seq_record.id +':2'
            print seq_record.seq[START_2:END_2]

if __name__ == '__main__' :
    parser = argparse.ArgumentParser()
    parser.add_argument('reads')
    args = parser.parse_args()
    read_reads(args.reads)

