#!/usr/bin/env python

import sys
import argparse
import numpy
import utils

def read_genome(fasta,k,kmer_overlap):
    with open(fasta) as f:
        prefix=''
        cnt=0
        for line in f:
            if '>' in line:
                prefix = line.strip().split('>')[1]
                cnt=0
            else:
                line=line.strip()
                while len(line)>=k:
                    cnt+=1
                    if not 'N' in line:
                        print '@'+prefix+'.'+str(cnt)
                        print line[:k]
                    line = line[k-kmer_overlap:]
                
                

         

if __name__ == '__main__' :
    parser = argparse.ArgumentParser()
    parser.add_argument('genome',help='genome fasta')
    parser.add_argument('kmer',help='size of kmers')
    parser.add_argument('kmer_overlap',help='overlap of adjacent kmers')
    args = parser.parse_args()
    read_genome(args.genome,int(args.kmer),int(args.kmer_overlap))

