#!/usr/bin/env python

import sys
import argparse
import numpy
import utils

def read_genome(fasta,k,kmer_overlap):
    with open(fasta) as f:
        for line in f:
            if '>' in line:
                continue
            else:
                line=line.strip()
                while len(line)>=k:
                    print line[:k]
                    line = line[k-kmer_overlap:]
                

if __name__ == '__main__' :
    parser = argparse.ArgumentParser()
    parser.add_argument('genome',help='genome fasta')
    parser.add_argument('kmer',help='size of kmers')
    parser.add_argument('kmer_overlap',help='overlap of adjacent kmers')
    args = parser.parse_args()
    read_genome(args.genome,int(args.kmer),int(args.kmer_overlap))

